baseURL: https://prudniak.netlify.app/
languageCode: en-us
title: Portfolio website for Piotr Rudniak
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Take a look!
    subtitle: Welcome to my portfolio website!
#      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Piotr Rudniak
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
#       street: 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    action: "https://formspree.io/f/xlevjzlw"
    method: "POST"
    formEmail: "prudniak.mam2023@london.edu"
    email:
      - email: prudniak.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 	+44 7467275816
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: LBS
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Prudniak/My_website_PR
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/piotr-rudniak
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: My projects
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
#    subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: Piotr_pic.jpg
        subtitle: Brief introduction
        title: About me
        url: blogs/about_me_v01
      - image: pic_p05.jpg
        subtitle: Download
        title: My CV
        buttonCV: Download
        url: "blogs/PiotrRudniak_resume.pdf"
      - image: pic_p04.jpg
        subtitle: Exploratory data analysis
        title: Brexit vote analysis
        url: blogs/brexit
      - image: pic_p06.jpg
        subtitle: Emissions dataset
        title: Making animation
        url: blogs/animation
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: List of my projects
    enable: yes
    subtitle: "The purpose of this website is to present the analytical projects done by me so \r\n 
    far and provide the visitors with small portion of information about me as well. Enjoy!"
    title: Website description
    url: blogs
